* 重要連絡 / Important Message
** 課題1の講評 / Comments on Report 1
2014年度TAの先崎さん・服部さんが [[file:report1-comment.pdf][課題1の講評]] を作成してくれました．
本講義の後半では「図面の完成度(=見やすさ・正確さ・明快さ)」も評価されます．

*必ず* 目を通して下さい．

Mr. Senzaki and Mr. Hattori, the 2014 TAs,  gave some comments on Report 1.
I would be helpful for improving your drawing skill, especially for the reports of the second-hard of this lecture, where the 'completeness' of the drawing sheet is also evaluated.

* 担当教員
長江 剛志(Nagae, Takeshi), 永井　大樹(Nagai, Hiroki)
E-mail: nagae＠m.tohoku.ac.ｊｐ 「＠」と「ｊｐ」を半角に置き換えること

* TA
服部悟 (Hattori, Satoru), 小田　泰之(Oda, Yasuyuki)
E-mail: hattori.satoru＠aero.mech.tohoku.ac.ｊｐ, oda.yasuyuki＠aero.mech.tohoku.ac.ｊｐ 「＠」と「ｊｐ」を半角に置き換えること

  
* 製図用ソフトウェア SolidWorks のダウンロードサイト
http://cad3d.mech.tohoku.ac.jp から 「3年生はこちらへ」
アクセスのためのユーザー名とパスワードは講義中に案内する．

* スケジュール(前半)
- 10/7 :: 第1回 ガイダンス，Solidworks のインストール方法およびチュートリアルの利用方法
          以下の点に注意すること：
  - 研究室等で利用されるPCは「ネットワークライセンス」を利用する．
    If you use the PCs in the lab, use the "Network License."
  - 「計画および製図II」の受講者が個人のPCにインストールする場合は「スチューデントアクセス」を利用する
    （受講者が研究室のPCにインストールする場合は，ネットワークライセンスを利用する）
    スチューデントアクセスのシリアル番号を記載した PDF ファイル(=student_access20**.pdf=)の閲覧パスワードは講義中に案内する．
    If you use your own PC, use the "Student Access." The serial ID is described in =student_access20**.pdf=, whose password 
    would be announced in the lecture.
  - 課題1: [[tutorial.org][「初めての部品作成」および「初めての図面作成」]]を読んで部品を作成し，部品図を提出せよ
    (提出期限：10/21. 提出方法：印刷して教室に持参)．
    *Report 1*: Build the part and submit the printed part drawing, according to 
    "Making My First Part" and "Making My First Drawing," which could be found in the SolidWorks Resource tab.
    http://help.solidworks.com/2014/English/SolidWorks/sldworks/r_solidworks_resources.htm
  - 部品図作成に当たっては [[file:report1-comment.pdf][課題1の講評]] を必ず読むこと．
    Refer the comments on Report 1.
- 10/14 :: 休講
           Cancellation.
  - SolidWorks がインストールできないなどの対応を希望する学生は，長江およびTAの二人にその旨をメールで知らせること
    If you found any problem in installation of SolidWorks, feel free to ask Dr. Nagae and two TAs by E-mail.
  - 特に対応を希望しない学生は，各自の環境で課題1に取り組むこと
    Otherwise, work by yourself.
- 10/21 :: 第2回 チュートリアルの図面提出，レイアウトスケッチの利用方法の解説，基本形状の課題発表
           III. Submit Report 1 and open the Report 2.
  - 課題1提出：(「初めての図面作成」)の図面を *印刷して持参* すること．
    Submit Report 1 (the printed part drawing).
    
  - *課題2*: [[file:2014-Exercise2.pdf][課題2ファイル]] に基づいて基本形状の部品を作成し，その部品ファイルを提出せよ(*提出期限: 11月4日*. 提出方法: メール. *下記参照*. )．
    なお，このファイルを開くためには，SolidWorks2014のインストールガイド(guide2014.pdf)を開くのと同じパスワードが必要．
    
    *Report 2*: Build the basic shapes (基本形状) in [[file:2014-Exercise2.pdf][Report 2 file]] and submit their part files by e-mailp. Deadline is *11/4*.
    The password for the Report 2 file is equivalent to that for opening the Installation Guide (guide2014.pdf).

  - 課題は下記に従い *メール* で提出すること．ルールを守らない場合は *減点* する．
    Submit the part files by e-mail according to the following rules. Violations would deduct the mark.
    1. 宛先は長江と2名のTAとせよ．
       The e-mail should be sent to Dr. Nagae and two TAs.
    2. 件名は *「H27製図II 課題2 B3TB9999 青葉一郎」* とせよ(B3TB9999と青葉一郎を自分の学籍番号に置き換えること)
       The subject should be "2015 Design and Drawing, B3TB****, Your Name" (replace * to your student ID).
    3. 課題2-1, 課題2-2 ともに *zip形式* でアーカイブ＆圧縮し，
       ファイル名を *「H27製図II-課題2-B3B9999.zip」* とせよ(IIはアルファベット大文字Iを2つ．区切り記号は半角ハイフン．)
       Every files should be archived and compressed as a single zip file.
       The file name should be "2015Design_and_Drawing-Rep2-B3TB****.zip"
    4. 本文は標準的なビジネスレターの形式(宛先，自分の学籍番号・氏名，用件)とする．下記を参考に添付ファイルの内容を記載せよ．
       The e-mail body should be formed as a standard business letter.
       You have to describe the list of contents of the zip file in the body of e-mail.
       「長江先生，服部さん，小田さん：
       B3TB9999 青葉一郎 です．
       製図IIの課題2として，
       以下の6個のファイルを zip 形式で圧縮した report2.zip を提出します．よろしくお願いいたします．」
       1. Kihon-A.sldprt (基本形状A)
       2. Kihon-B.sldprt (基本形状B)
       3. Kihon-C.sldprt (基本形状C)
       4. Kihon-D.sldprt (基本形状D)
       5. Kihon-E.sldprt (基本形状E)
       6. Kihon-G.sldprt (基本形状F)
    5. メールでの提出が不可能な場合は，ファイルの入った USB メモリを提出期限の13時に講義室へ持参せよ．
       If you can not submit the file by E-mail, put the file into your own USB memory and bring it to the lecture room at 1PM of the due date.
       
  - 長江が作成した課題2の基本形状ごとの体積と表面積は以下の通り：
    Use the following volume and surface area of each basic shape as a checksum.
    |-------------+------------+--------------+--------------|
    | 形状(Shape) | 体積(Volume, mm^3) | 表面積(Surface area, mm^2) | 備考(Remark) |
    |-------------+------------+--------------+--------------|
    | 基本形状A   |   90000.00 |     23189.05 |              |
    | 基本形状B   |  106465.71 |     25730.05 |              |
    | 基本形状C   |   47390.03 |     10482.76 |              |
    | 基本形状D   |  134575.22 |     21479.84 |              |
    | 基本形状E   |   92365.71 |     23913.02 |              |
    | 基本形状F   |  122342.04 |     24962.23 |              |
    | 基本形状G   |   51258.77 |     17682.69 | 13.10.24修正 |
    | 基本形状H   |   44210.27 |     13369.38 |              |
    | 基本形状I   |   56589.05 |     20733.85 |              |
    | 基本形状J   |  109348.67 |     26215.22 |              |
    |-------------+------------+--------------+--------------|
  - 10/28 :: 第3回 各自演習
             Work by yourself.
  - 11/4 :: 第4回 基本形状の課題提出
             Submit Report 2.
      - 課題2の提出などに問題がなければ出席は不要．
        Attendance is not mandatory if you do not have any question.
  - 11/11 :: 第5回 Geneva 機構の解説および課題発表
             Open the Report 3.
    - *課題3*: [[file:Exercise3.pdf][課題3ファイル]] を読んで組立ファイルを作成し，学務情報システム より提出せよ．この課題ファイルを開くためには，課題2と同じパスワードが必要 (提出期限: *11月25日*)

      *Report 3*: Build the Geneva Drive in [[file:Exercise3.pdf][Report 3 file]] and submit its *assembly file* via e-mail (nagae@m.tohoku.ac.jp). Deadline is *11/25*.
      - 提出ファイルは *アセンブリ・ファイル内に構成部品を保存したもの* か *アセンブリ・ファイルと部品ファイルを圧縮したもの* とする．
        Report should be submitted as either an assembly file that includes its whole components, or an archive file that includes an assembly file and its all part files.
  - 11/18 :: 第6回 各自演習
             Work by yourself.
  - 11/25 :: 第7回 課題3の提出．
             Submit Report 3.
             Report 3 should be submitted as either an assembly file that includes its whole components, or an archive file that includes an assembly file and its all part files.




* 前半の評価 / Evaluation
If you are an IMAC-U student and have question about evaluation, feel free to contact Nagae (nagae@m.tohoku.ac.jp).
    - 長江担当分の成績(100点満点)は，課題1〜3 の点数を用いて以下のように成績を評価
      する：
      1. 課題1を10点として，課題2(100点)と課題3(100点)の点数の合計を2で割ったもの
         に加えたものを「素点」とする．
      2. 「素点」が49点未満の場合は，「素点」+10点を「長江担当分の成績」とする
      3. 「素点」が50点以上59点未満の場合は，60点を「長江担当分の成績」とする
      4. 「素点」が100点を超えた場合，100点を「長江担当分の成績」とする．
    - 採点例
      - サボった場合：課題1(10点)，課題2-1(50点)のみ :: 
           素点は 10 + 50/2 = 35 で49点未満なので，35+10 = 45 点が長江担当分の成績．
      - 最低限の課題のみこなした場合：課題1(10点)，課題2-1(50点)，課題3-1(30点) :: 
           ・素点は 10 + (50+30)/2 = 50 で50点以上59点未満なので，60点が長江担当分の成績
      - 普通に課題に取り組んだ場合：課題1(10点)，課題2-1(50点)，課題2-2の基本形状E(40点)，課題3-1(30点)，課題3-2(10点)，課題3-3で動かないが部品・組立までできた機構1つ(10点) :: 
           ・素点は 10 + (50+40+30+10+10)/2 = 80 なので，80点が長江担当分の成績
      - よく頑張った場合：課題1(10点)，課題2-1(50点)，課題2-2の基本形状E,F(50点)，課題3-1(30点),課題3-2(10点)，課題3-3で適切に動作する機構1つ(20点) :: 
           ・素点は 10 + (50+50+30+10+20)/2 = 90 なので，90点が長江担当分の成績
      - ものすごく頑張った場合：課題1(10点)，課題2全て(100点)，課題3全て(100点) ::
           ・素点は 10 + (100+100)/2 = 110 なので，100点が長江担当分の成績

後半のスケジュールは12月以降に指示される．
